# golangci-lint config - https://golangci-lint.run
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly
  go: "1.24"  # golangci-lint v1.64 binary built with go1.24; override until golangci built with 1.25

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - exhaustive  # often noisy in tests
  settings:
    govet:
      enable:
        - shadow
    errcheck:
      check-type-assertions: true
      check-blank: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
