# golangci-lint config - https://golangci-lint.run
# v1.64 format (no version field, linters-settings)

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
  disable:
    - exhaustive

linters-settings:
  govet:
    enable:
      - shadow
  errcheck:
    check-type-assertions: true
    check-blank: true

issues:
  max-issues-per-linter: 50
  max-same-issues: 3
